### ISSUE TITLE
-Dspring.native.verify=false check not working

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#425]
Hi

I've been trying to deactivate the -Dspring.native.verify check, but it is not working.

The command I launch is:

`native-image --verbose -Dspring.native.remove-yaml-support=true -Dspring.native.verify=false -H:Name=$ARTIFACT --initialize-at-build-time=javax.el -H:ConfigurationFileDirectories=./ -H:ResourceConfigurationFiles=./resource-config.json -H:ReflectionConfigurationFiles=./reflect-config.json -H:DynamicProxyConfigurationFiles=./proxy-config.json -cp $CP $MAINCLASS`

And the output I still receive is:

`fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: ERROR: in 'myclass.class' these methods are directly invoking methods marked @Bean: [myService] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false.`

I'm using GraalVM v 20.3 for Java 8, and Spring GraalVM Native 0.8.3.

**Comment by aclement** [comment]
There was a time when the check for verification off wasn't in place for all routes to the verifier. This has been fixed, can you try with 0.8.5 instead of 0.8.3?

**Comment by khaeghar** [comment]
I changed to 0.8.5-SNAPSHOT and this happened:
```
myapp:16501]    classlist:   5,920.35 ms,  2.24 GB

   _____                     _                             _   __           __     _              
  / ___/    ____    _____   (_)   ____    ____ _          / | / /  ____ _  / /_   (_) _   __  ___ 
  \__ \    / __ \  / ___/  / /   / __ \  / __ `/         /  |/ /  / __ `/ / __/  / / | | / / / _ \
 ___/ /   / /_/ / / /     / /   / / / / / /_/ /         / /|  /  / /_/ / / /_   / /  | |/ / /  __/
/____/   / .___/ /_/     /_/   /_/ /_/  \__, /         /_/ |_/   \__,_/  \__/  /_/   |___/  \___/ 
        /_/                            /____/                                                     
Removing unused configurations
Verification turned on
Removing Yaml support
Removing XML support
Removing JMX support
Use -Dspring.native.verbose=true on native-image call to see more detailed information from the feature
   _____                     _                             _   __           __     _              
  / ___/    ____    _____   (_)   ____    ____ _          / | / /  ____ _  / /_   (_) _   __  ___ 
  \__ \    / __ \  / ___/  / /   / __ \  / __ `/         /  |/ /  / __ `/ / __/  / / | | / / / _ \
 ___/ /   / /_/ / / /     / /   / / / / / /_/ /         / /|  /  / /_/ / / /_   / /  | |/ / /  __/
/____/   / .___/ /_/     /_/   /_/ /_/  \__, /         /_/ |_/   \__,_/  \__/  /_/   |___/  \___/ 
        /_/                            /____/                                                     
Removing unused configurations
Verification turned on
Removing Yaml support
Removing XML support
Removing JMX support
Use -Dspring.native.verbose=true on native-image call to see more detailed information from the feature
[restapp2:16501]        setup:     582.85 ms,  2.24 GB
Error: Already registered: java.beans.Introspector.findCustomizerClass(Class)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1647)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1397)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1358)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1317)
cat: output.txt: No such file or directory
FAILURE: an error occurred when compiling the native-image.
```

It's the exact same app, the same command, 2.4.1 version of Spring boot. The only thing changed is the Spring GraalVM Native library version, from 0.8.3 to 0.8.5. 

Should I try with the 0.9.0 with 2.4.1 of Spring Boot too?

**Comment by aclement** [comment]
I've never seen that error before. First I would say try with 0.8.5 release, not snapshot. Then I'd say I probably need a pointer to the repository? (or test sample). It is possible that the application is using something that just isn't supported yet, but hard to tell.  Or you could go back to the 0.8.3 and refactor your app so it doesn't trigger the verification problem since it looks like it is an issue in the application classes rather than in a dependency (which would be harder to refactor). I'm half thinking the verification problem is just masking the Introspector issue.

**Comment by khaeghar** [comment]
Hi,

For the second error I found what was happening. I had in my BOOT-INF folder two spring-graalvm-native versions. When erased the one that was not needed, it finally started the compilation again.

I changed the version to the 0.8.5 one, and the first error reported about the verification still occurs. I refactored my code so it won't throws this error, the library that's throwing this is one of io.github.resilience4j

```
Processing type io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration
Analyzing io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration reached by [[Ctx:io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration-FromSpringFactoriesKey]]
found 2 hints on io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration:
1) Hint{[osbac.ConditionalOnClass],inferred=[igrb.Bulkhead:ACS(CLS),osccsr.RefreshScope:ACS(CLS)]}
2) Hint{[osbac.ConditionalOnClass,osca.Conditional],inferred=[osbac.OnClassCondition:ACS(CLS CONS)]}
processing hint Hint{[osbac.ConditionalOnClass],inferred=[igrb.Bulkhead:ACS(CLS),osccsr.RefreshScope:ACS(CLS)]}
attempting registration of 2 inferred types
attempting registration of 2 elements of annotation hint chain
processing hint Hint{[osbac.ConditionalOnClass,osca.Conditional],inferred=[osbac.OnClassCondition:ACS(CLS CONS)]}
attempting registration of 1 inferred types
attempting registration of 3 elements of annotation hint chain
>processHierarchy igrba.RefreshScopedBulkheadAutoConfiguration
Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: ERROR: in 'io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration' these methods are directly invoking methods marked @Bean: [bulkheadRegistry, threadPoolBulkheadRegistry] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:483)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:350)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:509)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.IllegalStateException: ERROR: in 'io.github.resilience4j.bulkhead.autoconfigure.RefreshScopedBulkheadAutoConfiguration' these methods are directly invoking methods marked @Bean: [bulkheadRegistry, threadPoolBulkheadRegistry] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false.
	at org.springframework.graalvm.type.Type.verifyComponent(Type.java:2273)
	at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1282)
	at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:960)
	at org.springframework.graalvm.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:950)
	at org.springframework.graalvm.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:849)
	at org.springframework.graalvm.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:714)
	at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:130)
	at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:107)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1647)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1397)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1358)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1317)
cat: output.txt: No such file or directory
FAILURE: an error occurred when compiling the native-image.
```


The command I'm executing right now is the following one: 

```
native-image --verbose -Dspring.native.verify=false -H:Name=$ARTIFACT --initialize-at-build-time=javax.el -Dspring.native.remove-yaml-support=true -H:ConfigurationFileDirectories=./ -H:ResourceConfigurationFiles=./resource-config.json -H:ReflectionConfigurationFiles=./reflect-config.json -H:DynamicProxyConfigurationFiles=./proxy-config.json -cp $CP $MAINCLASS  -Dspring.native.verbose=true
```

**Comment by khaeghar** [comment]
Nvm

It finally worked after updating the 0.8.5 version of GraalVM. My bad.

Sorry for the inconvenience and thanks for the help!

**Comment by sdeleuze** [comment]
Np thanks for the update.
